# This matches the Key you made in Phase 1
sonar.projectKey=test-cicd

# This tells Sonar to look at all files in this folder
sonar.sources=.

# If you have specific folders to ignore (like libraries), list them here
sonar.exclusions=**/node_modules/**,**/dist/**
